# Generated by Django 3.1.5 on 2021-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.CharField(choices=[('Lusaka', 'Lusaka'), ('Western', 'Western'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Luapula', 'Luapula'), ('Copperbelt', 'Copperbelt'), ('Muchinga', 'Muchinga'), ('Central', 'Central'), ('Eastern', 'Eastern')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('rnt', 'For Rent'), ('sal', 'For Sale'), ('sld', 'sold'), ('rtd', 'rented'), ('unv', 'unavaliable')], default='Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('ap', 'Apartment'), ('bds', 'Bedsitter'), ('com', 'Commercial'), ('con', 'Condo'), ('Cott', 'Cottage'), ('Dup', 'Duplex'), ('flt', 'Flat'), ('htl', 'Hotel'), ('ict', 'Incomplete House'), ('ld', 'Land'), ('lge', 'Lodge'), ('Mai', 'Maisonette'), ('Man', 'Mansion'), ('Mfh', 'Multi Family Home'), ('Mts', 'Multi Storey'), ('ofs', 'Office Space'), ('plt', 'Plot'), ('rnc', 'Ranch'), ('sfh', 'Single Family Home'), ('ths', 'Townhouse'), ('unt', 'Unit'), ('vil', 'Villa'), ('war', 'Warehouse')], default='Not Available', max_length=200),
        ),
    ]
