# Generated by Django 3.1.6 on 2021-02-17 22:21

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210217_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.StdImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
