# Generated by Django 3.1.6 on 2021-02-17 22:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210217_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
