# Generated by Django 3.1.6 on 2021-02-26 09:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210217_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.JPEGField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
