# Generated by Django 3.1.5 on 2021-01-25 02:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210125_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.JPEGField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
