# Generated by Django 3.1.5 on 2021-01-25 02:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210125_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
