# Generated by Django 3.1.5 on 2021-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210125_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Bedsitter', 'Bedsitter'), ('Commercial', 'Commercial'), ('Condo', 'Condo'), ('Cottage', 'Cottage'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Hotel', 'Hotel'), ('Incomplete House', 'Incomplete House'), ('Land', 'Land'), ('Lodge', 'Lodge'), ('Maisonette', 'Maisonette'), ('Man', 'Mansion'), ('Mansion', 'Multi Family Home'), ('Multi Storey', 'Multi Storey'), ('Office Space', 'Office Space'), ('Plot', 'Plot'), ('Ranch', 'Ranch'), ('Single Family Hom', 'Single Family Home'), ('Townhouse', 'Townhouse'), ('Unit', 'Unit'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], default='Not Available', max_length=200),
        ),
    ]
