# Generated by Django 3.1.5 on 2021-01-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210125_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('sold', 'sold'), ('rented', 'rented'), ('unavaliable', 'unavaliable')], default='Not Available', max_length=200),
        ),
    ]
