# Generated by Django 3.1.5 on 2021-01-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210125_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.CharField(choices=[('Lusaka', 'Lusaka'), ('Western', 'Western'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Luapula', 'Luapula'), ('Copperbelt', 'Copperbelt'), ('Muchinga', 'Muchinga'), ('Central', 'Central'), ('Eastern', 'Eastern')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('sold', 'sold'), ('rented', 'rented'), ('unavaliable', 'unavaliable')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Bedsitter', 'Bedsitter'), ('Commercial', 'Commercial'), ('Condo', 'Condo'), ('Cottage', 'Cottage'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Hotel', 'Hotel'), ('Incomplete House', 'Incomplete House'), ('Land', 'Land'), ('Lodge', 'Lodge'), ('Maisonette', 'Maisonette'), ('Man', 'Mansion'), ('Mansion', 'Multi Family Home'), ('Multi Storey', 'Multi Storey'), ('Office Space', 'Office Space'), ('Plot', 'Plot'), ('Ranch', 'Ranch'), ('Single Family Hom', 'Single Family Home'), ('Townhouse', 'Townhouse'), ('Unit', 'Unit'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], default='', max_length=200),
        ),
    ]
