# Generated by Django 3.1.6 on 2021-02-16 23:43

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo_main', '600x338', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
