# Generated by Django 3.1.6 on 2021-02-16 23:52

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20210216_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
