# Generated by Django 3.1.6 on 2021-02-17 00:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20210216_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=stdimage.models.JPEGField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
