# Generated by Django 3.1.5 on 2021-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(default='Not-available', max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(default='not-Available', max_length=20),
        ),
    ]
