# Generated by Django 3.1.5 on 2021-01-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20210123_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='is_mvp',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default='No Photo', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
