# Generated by Django 3.1.5 on 2021-01-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0008_auto_20210124_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
