# Generated by Django 3.1.5 on 2021-01-25 01:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0009_auto_20210124_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=stdimage.models.StdImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
