# Generated by Django 3.1.5 on 2021-01-25 02:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_auto_20210125_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=stdimage.models.JPEGField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
