# Generated by Django 3.1.5 on 2021-01-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0011_auto_20210125_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='is_mvp',
        ),
    ]
